# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Build stage
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json tsconfig.json bun.lock .
RUN npm install --ignore-scripts

# Copy source and transpile
COPY . .
RUN npx tsc -p tsconfig.json && chmod +x build/index.js

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built application
COPY --from=build /app/build ./build

# Install production dependencies without running prepare scripts
COPY package.json bun.lock .
RUN npm install --omit=dev --ignore-scripts

ENV NODE_ENV=production
ENTRYPOINT ["node", "build/index.js"]
